### ISSUE TITLE
NchooseK + mixture constraints fail

### ISSUE THREAD

**Issue by jsdiazpo** [basf/doe#9]
NchooseK constraint fails when in addition a mixture constraint (sum(x_i) = 1.0) is included. The warning `Sampling of points fulfilling this problem's constraints is not implemented` appears. The resulting design is a trivial collection of runs with a single input set to `1` with all the other to `0`. In the example code below, the goal is to have a simple linear design for a four-ingredient mixture (`x1+x2+x3+x4+x5=1`) with a maximum of three ingredients:
```python
num_inputs = 4
inputs = [f"x{i+1}" for i in range(num_inputs)]
print('Inputs\t   :', inputs)

# mixture constraint
constr1 = opti.LinearEquality(names=[x for x in inputs], lhs=[1 for _ in inputs], rhs=1)
print('Constraints:', constr1)
# n-choose-k
num_nCk_active = 2
constr2 = opti.NChooseK([x for x in inputs], max_active=num_nCk_active)

problem = opti.Problem(
    inputs=[opti.Continuous(x, domain=[0., 1.]) for x in inputs],
    outputs=[opti.Continuous("y")],
    constraints=[constr2, constr1],
)

doe = doe.find_local_max_ipopt(
        problem=problem,
        model_type="linear"
)
```

**Comment by Osburg** [comment]
Hi @jsdiazpo :),
You are right, I also get a design consisting only of corner points when I run your code example from above.
It is some time ago now and I did not go into the math again, but if I remember correctly, for a _linear_ model the D-optimal design consists only of corner points, which would mean that the method still works fine. 

We could check by just removing the NChooseK `constr2` constraint (which, I guess, is the reason you assume to cause the problems)
This gives me the following design.


x1 | x2 | x3 | x4
-- | -- | -- | --
-0.0 | -0.0 | 1.0 | -0.0
-0.0 | 1.0 | -0.0 | -0.0
-0.0 | -0.0 | 1.0 | -0.0
-0.0 | -0.0 | -0.0 | 1.0
-0.0 | 1.0 | -0.0 | -0.0
1.0 | -0.0 | -0.0 | -0.0
-0.0 | 1.0 | -0.0 | -0.0
-0.0 | -0.0 | -0.0 | 1.0

Compared to the case with the NChooseK constraint


x1 | x2 | x3 | x4
-- | -- | -- | --
0.0 | 1.0 | -0.0 | 0.0
1.0 | 0.0 | 0.0 | -0.0
0.0 | 0.0 | -0.0 | 1.0
0.0 | -0.0 | 0.0 | 1.0
1.0 | 0.0 | -0.0 | 0.0
-0.0 | 1.0 | 0.0 | 0.0
0.0 | -0.0 | 1.0 | 0.0
1.0 | 0.0 | 0.0 | -0.0

In both cases we get 2 the result is the same: 2 experiments in each corner!

I think for other models, e.g. a fully-quadratic model, we would expect to also get points on the faces of the simplex of feasible points. Looking at the same case with a fully-quadratic model we will see that also here the NChooseK constraint seems to cause no problems

First with the NChooseK constraint

```
problem = opti.Problem(
    inputs=[opti.Continuous(x, domain=[0., 1.]) for x in inputs],
    outputs=[opti.Continuous("y")],
    constraints=[constr2, constr1],
)

res = doe.find_local_max_ipopt(
        problem=problem,
        model_type="fully-quadratic"
)
```

We get 



x1 | x2 | x3 | x4
-- | -- | -- | --
0.5 | 0.5 | 0.0 | 0.0
0.5 | 0.0 | 0.0 | 0.5
0.0 | 0.0 | -0.0 | 1.0
0.0 | 0.5 | 0.0 | 0.5
0.5 | 0.0 | 0.5 | 0.0
0.0 | 0.5 | 0.5 | 0.0
0.5 | 0.5 | 0.0 | 0.0
0.5 | 0.0 | 0.0 | 0.5
0.0 | 0.0 | 0.5 | 0.5
0.0 | 0.5 | 0.0 | 0.5
0.5 | 0.0 | 0.5 | 0.0
0.0 | 0.5 | 0.5 | 0.0
-0.0 | 1.0 | 0.0 | 0.0
0.5 | 0.0 | 0.0 | 0.5
0.0 | 0.0 | 1.0 | -0.0
0.0 | 0.5 | 0.0 | 0.5
1.0 | 0.0 | -0.0 | 0.0
0.0 | 0.5 | 0.5 | 0.0

and without

x1 | x2 | x3 | x4
-- | -- | -- | --
0.5 | -0.0 | -0.0 | 0.5
0.5 | 0.5 | -0.0 | -0.0
-0.0 | -0.0 | 0.5 | 0.5
0.5 | -0.0 | -0.0 | 0.5
-0.0 | 0.5 | 0.5 | -0.0
-0.0 | -0.0 | 0.5 | 0.5
0.5 | -0.0 | 0.5 | -0.0
0.5 | 0.5 | -0.0 | -0.0
-0.0 | 1.0 | -0.0 | -0.0
-0.0 | -0.0 | 1.0 | -0.0
-0.0 | 0.5 | 0.5 | -0.0
1.0 | -0.0 | -0.0 | -0.0
0.5 | -0.0 | 0.5 | -0.0
-0.0 | -0.0 | -0.0 | 1.0
-0.0 | 0.5 | -0.0 | 0.5
-0.0 | 0.5 | 0.5 | -0.0
-0.0 | 0.5 | -0.0 | 0.5
-0.0 | -0.0 | 0.5 | 0.5

In both cases we have 4 corner points and the rest spread over the middle points of the edges of our simplex. As far as I remember this is the expected behaviour. This means: I think in your example the D-optimal design anyways fulfills your NChooseK constraint. Do you agree? Did I miss sth?

**Comment by Osburg** [comment]
Ah, and I forgot to write sth about the warning you received: Indeed there is no implementation for sampling points (initial guesses for the optimizer) that fullfill NChooseK constraints and other constraints at the same time. However, all constraints are passed to IPOPT and it will try to find a design that respects all constraints. Since the fix of your last issue #6 you should get another warning if such a design cannot be achieved.

**Comment by jsdiazpo** [comment]
hi @Osburg, thanks for the clear explanation. I agree that I should have tested a design other than linear. One thing that still bothers me, though, is that the returned design includes several sets of repeated experiments instead of multi-component mixtures. I am working with a more extended case: 13 inputs, maximum 5 can be present, `num_inputs = 13` and `num_nCk_active = 5` in the code above. For a design with `linear-and-interactions` model type, I get back a 95-run design with almost all binary mixtures, not a single multi-component (3, 4, or 5) mixture. I guess they are reduce the D-optimality score but I wish to get some multi-component mixtures instead of duplicates of existing corner runs.

**Comment by Osburg** [comment]
As you said, I also think that a model made out of corner points and binary (50:50) mixtures defines the D-optimal design. However, if you are willing to accept a worse D-optimality score, you could easily fix this by adding higher order interactions to the model you optimize for. At least intuitively I would say that you can expect n nonzero components if you add n-th order interactions. I added a minimal example below. There we have 3 inputs, a mixture constraint and all interactions up to the 3rd order (i.e. the highest possible order in this case). I think the result looks similar to what you want.

```
import opti
import numpy as np
import doe

problem = opti.Problem(
   inputs = opti.Parameters([opti.Continuous(f"x{i+1}", [0, 1]) for i in range(3)]),
   outputs = [opti.Continuous("y")],
   constraints = [
        opti.LinearEquality(names=[f"x{i+1}" for i in range(3)], rhs=1),
   ]
)

res = doe.find_local_max_ipopt(problem, "x1 + x2 + x3 + x1:x2 + x1:x3 + x2:x3 + x1:x2:x3", delta=1e-3)

print(np.round(res,2))
```

Resulting design

 x1 |  x2 |  x3
--|--|--
| -0.00|  1.00| -0.00
| -0.00| -0.00|  1.00
|  0.50| -0.00|  0.50
| -0.00| -0.00|  1.00
|  0.50| -0.00|  0.50
| -0.00|  0.50|  0.50
|  0.34|  0.34|  0.32
|  0.34|  0.34|  0.32
|  1.00| -0.00| -0.00
| -0.00|  0.50|  0.50
|  0.50|  0.50| -0.00

**Comment by jsdiazpo** [comment]
this is a clever approach, I am willing to sacrifice some D-optimality to explore not-repeated configurations away from the corners, thanks!
